<a href="https://colab.research.google.com/github/ASO1801040/AI_tech2020/blob/master/20201000AI0205_selectAlgo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.utils.testing import all_estimators
import warnings
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

In [38]:
import urllib.request as req
url = "https://github.com/pandas-dev/pandas/raw/master/pandas/tests/io/data/csv/iris.csv"
savefile = "iris.csv"
req.urlretrieve(url, savefile)
iris_data = pd.read_csv(savefile, encoding="utf-8")
iris_data.head

<bound method NDFrame.head of      SepalLength  SepalWidth  PetalLength  PetalWidth            Name
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]>

In [39]:
y = iris_data.loc[:,"Name"]
x = iris_data.loc[:,["SepalLength","SepalWidth","PetalLength","PetalWidth"]]

print(y.head)
print(x.head)

<bound method NDFrame.head of 0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Name, Length: 150, dtype: object>
<bound method NDFrame.head of      SepalLength  SepalWidth  PetalLength  PetalWidth
0            5.1         3.5          1.4         0.2
1            4.9         3.0          1.4         0.2
2            4.7         3.2          1.3         0.2
3            4.6         3.1          1.5         0.2
4            5.0         3.6          1.4         0.2
..           ...         ...          ...         ...
145          6.7         3.0          5.2         2.3
146          6.3         2.5          5.0         1.9
147          6.5         3.0          5.2         2.0
148          6.2         3.4          5.4         2.3
149          5.9         3.0          5.1         1.8

[150 rows

In [40]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, train_size = 0.8, shuffle = True)
print(x_train.head)
print(x_test.head)
print(y_train.head)
print(y_test.head)

<bound method NDFrame.head of      SepalLength  SepalWidth  PetalLength  PetalWidth
140          6.7         3.1          5.6         2.4
116          6.5         3.0          5.5         1.8
85           6.0         3.4          4.5         1.6
47           4.6         3.2          1.4         0.2
138          6.0         3.0          4.8         1.8
..           ...         ...          ...         ...
22           4.6         3.6          1.0         0.2
41           4.5         2.3          1.3         0.3
76           6.8         2.8          4.8         1.4
105          7.6         3.0          6.6         2.1
107          7.3         2.9          6.3         1.8

[120 rows x 4 columns]>
<bound method NDFrame.head of      SepalLength  SepalWidth  PetalLength  PetalWidth
103          6.3         2.9          5.6         1.8
35           5.0         3.2          1.2         0.2
86           6.7         3.1          4.7         1.5
109          7.2         3.6          6.1         2

In [41]:
allAlgorithms = all_estimators(type_filter="classifier")
warnings.filterwarnings('ignore')

In [42]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [43]:
Kfold_cv = KFold( n_splits = 5 , shuffle=True)

for(name , algorithm) in allAlgorithms:
  try:
    clf = algorithm()
    if hasattr(clf,"score"):
      scores = cross_val_score(clf, x, y, cv=Kfold_cv)
      print(name,'の正解率=')
      print(scores)

  except Exception as e:
    print(e)

AdaBoostClassifier の正解率=
[0.96666667 0.93333333 1.         0.96666667 0.9       ]
BaggingClassifier の正解率=
[0.93333333 0.9        0.96666667 0.96666667 1.        ]
BernoulliNB の正解率=
[0.23333333 0.16666667 0.3        0.26666667 0.16666667]
CalibratedClassifierCV の正解率=
[0.86666667 0.96666667 0.8        0.93333333 0.93333333]
CategoricalNB の正解率=
[0.86666667 0.93333333 0.93333333 0.96666667 0.93333333]
CheckingClassifier の正解率=
[nan nan nan nan nan]
__init__() missing 1 required positional argument: 'base_estimator'
ComplementNB の正解率=
[0.56666667 0.7        0.7        0.66666667 0.7       ]
DecisionTreeClassifier の正解率=
[0.93333333 0.93333333 0.93333333 0.96666667 0.96666667]
DummyClassifier の正解率=
[0.4 0.3 0.4 0.2 0.3]
ExtraTreeClassifier の正解率=
[0.96666667 0.93333333 0.96666667 0.96666667 0.83333333]
ExtraTreesClassifier の正解率=
[0.96666667 0.93333333 0.93333333 0.96666667 0.96666667]
GaussianNB の正解率=
[1.         0.96666667 1.         0.93333333 0.86666667]
GaussianProcessClassifier の正解率=
[1.  

In [44]:
parameters = [
              {'C':[1,10,100,1000],"kernel":["linear"]},
              {'C':[1,10,100,1000],"kernel":["rbf"],"gamma":[0.001,0.0001]},
              {'C':[1,10,100,1000],"kernel":["sigmoid"],"gamma":[0.001,0.0001]}
]

clf = SVC()
clf.fit(x_train,y_train)
y_pred = clf.predict(x_test)
print("普通の学習の正解率　=", accuracy_score(y_test, y_pred))

kfold_cv = KFold( n_splits=5, shuffle=True)
clf_grid = GridSearchCV( SVC(), parameters, cv = kfold_cv)
clf_grid.fit(x_train, y_train)
print("最適なパラメーター = ", clf_grid.best_estimator_)

y_pred = clf_grid.predict(x_test)
print("グリッドサーチの正解率 = ", accuracy_score(y_test, y_pred))

普通の学習の正解率　= 1.0
最適なパラメーター =  SVC(C=1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)
グリッドサーチの正解率 =  1.0


In [45]:
import numpy as np

In [46]:
a = np.array([1,2,3,4,5])

print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [47]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [50]:
print(np.zeros(10))
print(np.zeros((3,2)))
print(np.ones(2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1.]


In [51]:
np.arange(5)
np.arange(2,9)
np.arange(5,8,0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5])

In [52]:
a = np.array([1,2,3,4,5])
b = a*2
print(b)
x = np.arange(10)
y = 3*x + 5
print(y)

[ 2  4  6  8 10]
[ 5  8 11 14 17 20 23 26 29 32]


In [53]:
a =np.array([[1,2,3],[4,5,6]])
print(a)
print(a.shape)

b= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [54]:
a = np.array([ [1,2,3],[4,5,6]])
print("a=",a)
b = a.flatten()
print("b=",b)

a = np.array([ [1,2,3],[4,5,6]])
print("a=",a)
b = a.reshape(3,2)
print("b=",b)



a= [[1 2 3]
 [4 5 6]]
b= [1 2 3 4 5 6]
a= [[1 2 3]
 [4 5 6]]
b= [[1 2]
 [3 4]
 [5 6]]


In [55]:
v = np.array([[1,2,3],[4,5,6],[7,8,9]])
a =v[0]
print(a)
b = v[1:]
print(b)
c = v[:,0]
print(c) 

[1 2 3]
[[4 5 6]
 [7 8 9]]
[1 4 7]
